Web/Areas/Administrator/Controllers/BlogCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Domain.Shop.Dto.BlogCategories;
using Domain.Shop.Entities;
using Domain.Shop.IRepositories;
using Infrastructure.Common;
using Infrastructure.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Web.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [BaseAuthorization]
    public class BlogCategoryController : BaseController
    {
        private IBlogCategoryRepository blogCategoryRepository;
        public BlogCategoryController(IBlogCategoryRepository blogCategoryRepository)
        {
            this.blogCategoryRepository = blogCategoryRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<BlogCategoryViewModel> blogCategories = blogCategoryRepository.GetBlogCategoryViewModels();
            blogCategories = BlogCategoryViewModel.GetTreeBlogCategoryViewModels(blogCategories);
            return View(blogCategories);
        }
        private void SetComboData(string HierarchyCode = null)
        {
            var blogCategoryQuery = blogCategoryRepository.All;
            if (!string.IsNullOrEmpty(HierarchyCode))
            {
                blogCategoryQuery = blogCategoryQuery.Where(p => !p.HierarchyCode.StartsWith(HierarchyCode));
            }
            ViewBag.blogCategories = blogCategoryQuery.OrderBy(p => p.HierarchyCode).Select(p => new SelectListItem
            {
                Text = p.BlogCategoryName,
                Value = p.HierarchyCode
            }).ToList();
        }
        public ActionResult Create()
        {
            SetComboData();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BlogCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!blogCategoryRepository.CheckNewSlug(model.Slug))
                    {
                        model.Id = Guid.NewGuid().ToString();
                        BlogCategory blogCategory = new BlogCategory();
                        PropertyCopy.Copy(model, blogCategory);
                        blogCategory.HierarchyCode = blogCategoryRepository.GenerateHierarchyCode(model.ParentHierarchyCode);
                        blogCategoryRepository.Add(blogCategory);
                        blogCategoryRepository.Save(requestContext);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        SetComboData();
                        return View();
                    }
                }
                catch (Exception)
                {
                    SetComboData();
                    return View();
                }
            }
            SetComboData();
            return View();
        }
        [HttpPost]
        public bool Delete(string id)
        {
            try
            {
                BlogCategory blogCategory = blogCategoryRepository.Single(p => p.Id == id, null);
                if (blogCategoryRepository.CanDeleteBlogCategory(blogCategory.HierarchyCode))
                {
                    blogCategoryRepository.Delete(blogCategory);
                    blogCategoryRepository.Save(requestContext);
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception )
            {
                return false;
            }

        }
        public ActionResult Update(string id)
        {
            var model = blogCategoryRepository.GetBlogCategoryViewModel(id);
            SetComboData(model.HierarchyCode);
            model.ParentHierarchyCode = model.HierarchyCode.Substring(0, model.HierarchyCode.Length - Domain.Common.Consts.Infrastructure.HierarchyCodeLength);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(BlogCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!blogCategoryRepository.CheckNewSlug(model.Slug))
                    {
                        BlogCategory blogCategory = blogCategoryRepository.Single(p => p.Id == model.Id, null);
                        List<string> excludeProperty = new List<string>() { "Id", "HierarchyCode" };
                        PropertyCopy.Copy(model, blogCategory, excludeProperty);
                        string CurrentHierarchyParent = blogCategory.HierarchyCode.Substring(0, blogCategory.HierarchyCode.Length - Domain.Common.Consts.Infrastructure.HierarchyCodeLength);
                        if (string.IsNullOrEmpty(model.ParentHierarchyCode) ? !string.IsNullOrEmpty(CurrentHierarchyParent) : model.ParentHierarchyCode != CurrentHierarchyParent)
                        {
                            var HierarchyCode = blogCategoryRepository.GenerateHierarchyCode(model.ParentHierarchyCode);
                            var ChildBlogCategories = blogCategoryRepository.GetChildBlogCategories(blogCategory.HierarchyCode);
                            foreach (BlogCategory item in ChildBlogCategories)
                            {
                                item.HierarchyCode = model.ParentHierarchyCode + item.HierarchyCode.Substring(HierarchyCode.Length);
                            }
                            blogCategory.HierarchyCode = HierarchyCode;
                        }
                        blogCategoryRepository.Update(blogCategory);
                        blogCategoryRepository.Save(requestContext);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        SetComboData();
                        return View();
                    }
                }
                catch (Exception)
                {
                    SetComboData(model.HierarchyCode);
                    return View();
                }
            }
            SetComboData(model.HierarchyCode);
            return View();
        }
    }
}

Web/Areas/Administrator/Views/BlogCategory/Create.cshtml
@model Domain.Shop.Dto.BlogCategories.BlogCategoryViewModel
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <form class="form-horizontal" method="post" action="@Url.ActionLink("Create")" asp-antiforgery="true">
                    <div class="card-header">
                        <h5 class="card-title">Thêm mới danh mục Blog</h5>
                    </div>

                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="ParentHierarchyCode" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <select asp-for="ParentHierarchyCode" asp-items="(List<SelectListItem>)ViewBag.blogCategories" class="blog-categories-select" style="width: 100%;">
                                        <option></option>
                                    </select>
                                    <span asp-validation-for="ParentHierarchyCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="BlogCategoryName" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="BlogCategoryName" class="form-control" id="blog-category-name" onchange="ChangeToSlug();" />
                                    <span asp-validation-for="BlogCategoryName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Slug" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Slug" class="form-control" id="slug" />
                                    <span asp-validation-for="Slug" class="text-danger"></span>
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="card-footer">
                        <a href="@Url.ActionLink("Index")" role="button" class="btn btn-default">Hủy</a>
                        <button type="submit" class="btn btn-info pull-right float-right">Thêm mới</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section Scripts {
    <script type="text/javascript">$('.blog-categories-select').select2({
            allowClear: true,
            placeholder: 'Chọn danh mục Blog cha'
        });
        const ChangeToSlug=() => {
            var str = document.getElementById('blog-category-name').value;
            str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
            str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
            str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
            str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
            str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
            str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
            str = str.replace(/đ/g, "d");
            str = str.replace(/À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ/g, "A");
            str = str.replace(/È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ/g, "E");
            str = str.replace(/Ì|Í|Ị|Ỉ|Ĩ/g, "I");
            str = str.replace(/Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ/g, "O");
            str = str.replace(/Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ/g, "U");
            str = str.replace(/Ỳ|Ý|Ỵ|Ỷ|Ỹ/g, "Y");
            str = str.replace(/Đ/g, "D");
            str = str.replace(/\s+/g, " ");
            str = str.replace(/\s/g, "-");
            document.getElementById('slug').value = str;
        };</script>
}

Web/Areas/Administrator/Views/BlogCategory/Index.cshtml
@model IEnumerable<Domain.Shop.Dto.BlogCategories.BlogCategoryViewModel>
@section Styles {
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <style type="text/css">

        #table-blog-categories .expanded .collapsed {
            display: none;
        }

        #table-blog-categories .collapsed .expanded {
            display: none;
        }

        #table-blog-categories_info {
            display: none;
        }
    </style>
}
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Danh sách danh mục Blog</h5>
                    <div class="card-tools">

                        <a href="@Url.ActionLink("Create")" role="button" class="btn bg-gradient-success btn-sm">
                            Thêm mới
                        </a>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body" style="overflow-x: auto;">
                    <table id="table-blog-categories" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 30px;"></th>
                                <th>Tên danh mục Blog</th>
                                <th>Slug</th>
                                <th style="width: 80px; "></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <partial name="_TableRow" model="item" />
                            }
                        </tbody>
                    </table>
                    <!-- /.row -->
                </div>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section Scripts
{

    <!-- page script -->
    <script>
    $(function () {
        $('#table-blog-categories').DataTable({
			ordering: false,
			paging: false,
			searching: false,
			fixedColumns: {
				leftColumns: 0,
				rightColumns: 4
			}
		});
    });
    function Delete(id){
		var r = confirm("Bạn có chắc chắn muốn xóa menu này?");
        if (r == true) {
            $.ajax(
            {
                type: "POST",
                url: '@Url.ActionLink("Delete", "BlogCategory")',
                data: {
                    id: id
                },
                error: function (result) {
                    alert("error");
                },
                success: function (result) {
                    if (result == true) {
                        window.location.reload();
                    }
                    else {
						alert("Không thể xóa menu này. Vui lòng xóa các menu con trước khi xóa!");
                    }
                }
            });
        }
	}

		function Toggle(hierarchyCode) {
			$("tr[data-hierarchy=" + hierarchyCode + "]").toggleClass("collapsed").toggleClass("expanded");
            $("#table-blog-categories tbody").each(function () {
				var hierarchy = $(this).data("child");
				if (hierarchy) {
					var parrentRow = $("tr[data-hierarchy=" + hierarchy + "]");
					if (parrentRow.hasClass("collapsed") || !parrentRow.is(":visible")) {
						$(this).hide();
					} else {
						$(this).show();
					}
				}
			});
		}
    </script>
}

Web/Areas/Administrator/Views/BlogCategory/Update.cshtml
@model Domain.Shop.Dto.BlogCategories.BlogCategoryViewModel
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <form class="form-horizontal" method="post" action="@Url.ActionLink("Update")" asp-antiforgery="true">
                    <div class="card-header">
                        <h5 class="card-title">Cập nhật danh mục Blog</h5>
                    </div>
                    <!-- /.card-header -->

                    <div class="card-body">
                        <input asp-for="Id" hidden />
                        <input asp-for="HierarchyCode" hidden />
                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="ParentHierarchyCode" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <select asp-for="ParentHierarchyCode" asp-items="(List<SelectListItem>)ViewBag.blogCategories" class="blog-categories-select" style="width: 100%;">
                                        <option></option>
                                    </select>
                                    <span asp-validation-for="ParentHierarchyCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="BlogCategoryName" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="BlogCategoryName" class="form-control" id="blog-category-name" onchange="ChangeToSlug();" />
                                    <span asp-validation-for="BlogCategoryName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Slug" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Slug" class="form-control" id="slug" />
                                    <span asp-validation-for="Slug" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="card-footer">
                        <a href="@Url.ActionLink("Index")" role="button" class="btn btn-default">Huỷ</a>
                        <button type="submit" class="btn btn-info pull-right float-right">Cập nhật</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section Scripts {
    <script type="text/javascript">
		$(function () {
            $('.blog-categories-select').select2({
				allowClear: true,
				placeholder: 'Chọn danh mục Blog cha'
			});
        });
        const ChangeToSlug = () => {
            var str = document.getElementById('blog-category-name').value;
            str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
            str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
            str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
            str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
            str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
            str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
            str = str.replace(/đ/g, "d");
            str = str.replace(/À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ/g, "A");
            str = str.replace(/È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ/g, "E");
            str = str.replace(/Ì|Í|Ị|Ỉ|Ĩ/g, "I");
            str = str.replace(/Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ/g, "O");
            str = str.replace(/Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ/g, "U");
            str = str.replace(/Ỳ|Ý|Ỵ|Ỷ|Ỹ/g, "Y");
            str = str.replace(/Đ/g, "D");
            str = str.replace(/\s+/g, " ");
            str = str.replace(/\s/g, "-");
            document.getElementById('slug').value = str;
        };
    </script>
}

Web/Areas/Administrator/Views/BlogCategory/_TableRow.cshtml
@model Domain.Shop.Dto.BlogCategories.BlogCategoryViewModel
@{
    var HierarchyPrefix = "|";
    for (int i = 0; i < Model.HierarchyCode.Length / 5; i++)
    {
        HierarchyPrefix += "-";
    }
}
<tr data-hierarchy="@Model.HierarchyCode" class="expanded">
    <td>
        @if (Model.Childs.Count() > 0)
        {
            <span onclick="Toggle('@Model.HierarchyCode')" class="toggle-button expanded">
                <i class="far fa-minus-square"></i>
            </span>
            <span onclick="Toggle('@Model.HierarchyCode')" class="toggle-button collapsed">
                <i class="far fa-plus-square"></i>
            </span>
        }
    </td>
    <td>@HierarchyPrefix @Model.BlogCategoryName</td>
    <td>@HierarchyPrefix @Model.Slug</td>
    <td>
        <div class="btn-group">
            <a role="button" class="btn btn-info" href="@Url.ActionLink("Update", "BlogCategory", new { id = Model.Id })">
                <i class="fas fa-edit"></i>
            </a>
            <a role="button" class="btn btn-danger" href="#" onclick="Delete('@Model.Id')">
                <i class="fas fa-trash"></i>
            </a>
        </div>
    </td>
</tr>
@if (Model.Childs.Count() > 0)
{
    <tbody data-child="@Model.HierarchyCode">
        @foreach (var item in Model.Childs)
        {
            <partial name="_TableRow" model="item" />
        }
    </tbody>
}