Web/Areas/Administrator/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Application.Entities;
using Domain.Shop.Dto.Tags;
using Domain.Shop.Entities;
using Domain.Shop.IRepositories;
using Infrastructure.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Web.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [BaseAuthorization]
    public class TagController : BaseController
    {
        private readonly ITagRepository _tagRepository;
        private readonly IProductTagRepository _productTagRepository;
        public TagController(ITagRepository tagRepository, IProductTagRepository productTagRepository)
        {
            _tagRepository = tagRepository;
            _productTagRepository = productTagRepository;
        }
        public ActionResult Index()
        {
            return View(_tagRepository.GetTagViewModels());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _tagRepository.Add(new Tag()
                    {
                        Id = Guid.NewGuid().ToString(),
                        Name = model.Name
                    });
                    _tagRepository.Save(requestContext);

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View();
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public bool Delete(string id)
        {
            try
            {
                Tag tag = _tagRepository.Get(id);
                var productTagList = _productTagRepository.GetProductTagViewModelsByTagId(id).Select(s => s.Id).ToList();
                if (productTagList != null && productTagList.Count > 0)
                {
                    foreach (var item in productTagList)
                    {
                        _productTagRepository.Delete(item);
                    }
                }
                _productTagRepository.Save(requestContext);
                _tagRepository.Delete(tag);
                _tagRepository.Save(requestContext);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        public ActionResult Update(string id)
        {
            var model = _tagRepository.GetTagViewModel(id);
            if (model == null)
            {
                return View();
            }
            else
            {
                return View(model);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(TagViewModel tag)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Tag t = _tagRepository.All.Where(s => s.Id == tag.Id).First();
                    t.Name = tag.Name;
                    _tagRepository.Save(requestContext);
                }
                catch (Exception)
                {
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Web/Areas/Administrator/Views/Tag/Create.cshtml
@model Domain.Shop.Dto.Tags.TagViewModel
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <form class="form-horizontal" method="post" action="@Url.ActionLink("Create")" asp-antiforgery="true">
                    <div class="card-header">
                        <h5 class="card-title">Thêm mới Tag</h5>
                    </div>

                    <!-- /.card-header -->
                    <div class="card-body">

                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="Name" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="card-footer">
                        <a href="@Url.ActionLink("Index")" role="button" class="btn btn-default">Hủy</a>
                        <button type="submit" class="btn btn-info pull-right float-right">Thêm mới</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>

Web/Areas/Administrator/Views/Tag/Index.cshtml
@model IEnumerable<Domain.Shop.Dto.Tags.TagViewModel>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Danh sách Tag</h5>
                    <div class="card-tools">

                        <a href="@Url.ActionLink("Create")" role="button" class="btn bg-gradient-success btn-sm">
                            Thêm mới
                        </a>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body" style="overflow-x: auto;">
                    <table id="table-tag" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Tag Name</th>
                                <th style="width: 80px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>
                        <div class="btn-group">
                            <a role="button" class="btn btn-info" href="@Url.ActionLink("Update", "Tag", new { id = item.Id })">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a role="button" class="btn btn-danger" href="#" onclick="Delete('@item.Id')">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
}
                        </tbody>
                    </table>
                    <!-- /.row -->
                </div>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section Scripts
{

    <!-- page script -->
    <script>
    $(function () {
        $('#table-tag').DataTable({
			"columnDefs": [
				{ "orderable": false, "targets": 2 }
			]
		});
    });
    function Delete(id){
		var r = confirm("Bạn có chắc chắn muốn xóa tag này?");
        if (r == true) {
            $.ajax(
            {
                type: "POST",
                url: '@Url.ActionLink("Delete", "Tag")',
                data: {
                    id: id
                },
                error: function (result) {
                    alert("error");
                },
                success: function (result) {
                    if (result == true) {
                        window.location.reload();
                    }
                    else {
						alert("Có lỗi xảy ra, vui lòng thử lại sau!");
                    }
                }
            });
        }
    }
    </script>
}

Web/Areas/Administrator/Views/Tag/Update.cshtml
@model Domain.Shop.Dto.Tags.TagViewModel
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <form class="form-horizontal" method="post" action="@Url.ActionLink("Update")" asp-antiforgery="true">
                    <div class="card-header">
                        <h5 class="card-title">Cập nhật Tag</h5>
                    </div>
                    <!-- /.card-header -->

                    <div class="card-body">
                        <input asp-for="Id" hidden />
                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="Name" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="card-footer">
                        <a href="@Url.ActionLink("Index")" role="button" class="btn btn-default">Huỷ</a>
                        <button type="submit" class="btn btn-info pull-right float-right">Cập nhật</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
</section>